language: php

env: # important!

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

branches:
  only:
    - master
    - 2.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install
